### ISSUE TITLE
Objects lacking md5 sum will fail to download

### ISSUE THREAD

**Issue by oliverwm1** [VulcanClimateModeling/fv3config#124]
Not all GCS objects are guaranteed to have md5 hashes. In particular, composite objects will lack them: https://cloud.google.com/storage/docs/composite-objects#metadata.

So, using the `consistency='md5'` flag can resulting in failing downloads during `write_run_directory` if one of the assets is a GCS object without an `md5` hash. We should probably use a more relaxed check like `consistency='size'` or just remove it entirely.

https://github.com/VulcanClimateModeling/fv3config/blob/945d87c773f530ddeca9d2af4554cc0d3bc9fc7f/fv3config/filesystem.py#L36

Related: #70 dask/gcsfs#338

**Comment by nbren12** [comment]
Interesting. It looks like md5 is not Google's preferred checksum. They instead use "CRC" for every object. Perhaps "size" is good enough for now, but we could bring this up with GCSFS.
