### ISSUE TITLE
Command-line interface

### ISSUE THREAD

**Issue by mcgibbon** [VulcanClimateModeling/fv3config#3]
Would be nice to create run directories from the command line. May use [entrypoints](https://amir.rachum.com/blog/2017/07/28/python-entry-points/) for this. Should be able to create a run directory from a yaml file containing the configuration dictionary, at least. After that, maybe we can use click to specify options, or maybe that's more trouble than it's worth.

**Comment by nbren12** [comment]
It think this would be great to return to. Also, it would be nice some options like `--days` `--initial-conditions` for overriding the values in the fv3config.yaml which are not related to the model physics.
