### ISSUE TITLE
Allow config['initial_conditions']=None option

### ISSUE THREAD

**Issue by oliverwm1** [VulcanClimateModeling/fv3config#44]
There are cases where a user might want to specify all initial conditions files via the `patch_files` option (e.g. if the initial conditions files need to be renamed or they are not all coming from the same directory). However if one leaves `config['initial_conditions']` as `default`, the `INPUT` directory will be populated with irrelevant GFS initial conditions. The model won't use them if the namelist is set properly, but it's confusing.

**Comment by mcgibbon** [comment]
We discussed that you would use this change in a branch as a temporary measure. In the long run we want to do some more extensive changes, which we can discuss in #46.

**Comment by oliverwm1** [comment]
I found a workaround so I'm going to close this issue.
