### ISSUE TITLE
Let `run_docker` work with assets present on host system

### ISSUE THREAD

**Issue by nbren12** [VulcanClimateModeling/fv3config#48]
It would also be nice to make `run_docker` work with assets that are present on this host system, which can be symlinked in using bind_mounts.

**Comment by mcgibbon** [comment]
We discussed another possible option for this would be giving a helper routine to upload files to google cloud and provide the url of the config dict which uses those remote files. However, symlinking local paths is probably easier, so we can plan to do it that way when we tackle this.

**Comment by nbren12** [comment]
Indeed, that's why I opened #47, but I still think this would be a nice addition. It shouldn't be too hard to make a separate bind-mount for each asset.
